import { forwardRef } from "react";
import { type PetProfile } from "@/context/PetContext";
import { SP } from "@/components/SensorPage";
import pawLogo from "@/assets/paw-logo.png";

export const PdfTemplate = forwardRef<HTMLDivElement, { pet: PetProfile; timeline: string }>(
  ({ pet, timeline }, ref) => {
    return (
      <div 
        ref={ref} 
        style={{
          width: "210mm",
          minHeight: "297mm",
          backgroundColor: "#ffffff",
          color: "#000000",
          padding: "20mm",
          boxSizing: "border-box",
          fontFamily: "sans-serif"
        }}
      >
        <div style={{ display: "flex", alignItems: "center", borderBottom: "2px solid #163E38", paddingBottom: 16, marginBottom: 24 }}>
          <img src={pawLogo} style={{ width: 48, height: 48, marginRight: 16 }} />
          <div>
            <h1 style={{ margin: 0, fontSize: 24, color: "#163E38" }}>Pawsitive Diagnostics</h1>
            <p style={{ margin: 0, fontSize: 12, color: "#666" }}>Health Report • Generated for {timeline}</p>
          </div>
        </div>
        
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 32 }}>
          <div>
            <h2 style={{ margin: "0 0 8px", fontSize: 28, color: "#333" }}>{pet.name}</h2>
            <p style={{ margin: 0, fontSize: 14 }}>Breed: {pet.breedEn || "Shiba Inu"}</p>
            <p style={{ margin: 0, fontSize: 14 }}>Age: {pet.age} years</p>
          </div>
          <div style={{ textAlign: "right" }}>
            <h3 style={{ margin: "0 0 4px", fontSize: 16, color: "#163E38" }}>Overall Health</h3>
            <div style={{ fontSize: 32, fontWeight: "bold", color: "#4CAF50" }}>94%</div>
          </div>
        </div>

        <h3 style={{ borderBottom: "1px solid #eee", paddingBottom: 8 }}>Sensor Matrix Summary</h3>
        <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 16 }}>
          <thead>
            <tr style={{ backgroundColor: "#f5f5f5", textAlign: "left" }}>
              <th style={{ padding: 12, borderBottom: "1px solid #ddd" }}>Sensor</th>
              <th style={{ padding: 12, borderBottom: "1px solid #ddd" }}>Average</th>
              <th style={{ padding: 12, borderBottom: "1px solid #ddd" }}>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Body Temperature</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>38.7°C</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee", color: "#4CAF50" }}>Normal</td>
            </tr>
            <tr>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Activity / Motion</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>14,200 steps/day</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee", color: "#4CAF50" }}>Active</td>
            </tr>
            <tr>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>BarkSense AI</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Happy / Normal (92%)</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee", color: "#4CAF50" }}>Stable</td>
            </tr>
            <tr>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Skin & Coat</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Hydrated</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee", color: "#4CAF50" }}>Excellent</td>
            </tr>
            <tr>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Collar Pressure</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee" }}>Comfortable fit</td>
              <td style={{ padding: 12, borderBottom: "1px solid #eee", color: "#4CAF50" }}>Optimal</td>
            </tr>
          </tbody>
        </table>

        <div style={{ marginTop: 48, fontSize: 10, color: "#999", textAlign: "center" }}>
          This report is electronically generated by Pawsitive Diagnostics Smart Dog Care System.
        </div>
      </div>
    );
  }
);
